/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "TFT_Clock_1.h"
#include "TFT.h"
#include "SPI0_MOSI_aliases.h"
#include "SPI0_MOSI.h"
#include "SPI0_MISO_aliases.h"
#include "SPI0_MISO.h"
#include "I2C_SDA_aliases.h"
#include "I2C_SDA.h"
#include "SPI0_SCLK_aliases.h"
#include "SPI0_SCLK.h"
#include "SPI0.h"
#include "SPI0_PVT.h"
#include "I2C_SCL_aliases.h"
#include "I2C_SCL.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "Bootloadable.h"
#include "SPI_ISR.h"
#include "SPI_INTR_aliases.h"
#include "SPI_INTR.h"
#include "ACC1_ISR.h"
#include "ACC2_ISR.h"
#include "ACC_INT1_aliases.h"
#include "ACC_INT1.h"
#include "ACC_INT2_aliases.h"
#include "ACC_INT2.h"
#include "PWR_INT.h"
#include "nIRQ_aliases.h"
#include "nIRQ.h"
#include "SW_ISR.h"
#include "SW_USER_aliases.h"
#include "SW_USER.h"
#include "PWM.h"
#include "TFT_LED_PWR_aliases.h"
#include "TFT_LED_PWR.h"
#include "Buzzer_aliases.h"
#include "Buzzer.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "SPI0_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

